import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

/**
 * Blog posts.
 *
 * Files are authored (or generated by the blog-autogen pipeline) as plain
 * Markdown in src/content/posts/<YYYY-MM-DD>-<slug>.md. The schema is the
 * contract between that generator and the site: the generator's frontmatter
 * (title, summary, publishedDate, draft, author) must satisfy it, and the
 * optional fields let a human enrich a post by hand.
 */
const posts = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/posts" }),
  schema: ({ image }) =>
    z.object({
      /** Headline. Kept short so it renders on one or two lines on the OG card. */
      title: z.string().min(3).max(120),
      /** One-sentence meta description / social summary. */
      summary: z.string().min(10).max(320),
      /** Publish date. Accepts an ISO date string from the generator. */
      publishedDate: z.coerce.date(),
      /** Optional last-updated date; drives dateModified in Article JSON-LD. */
      updatedDate: z.coerce.date().optional(),
      /** Hidden from the built site until flipped to false. */
      draft: z.boolean().default(false),
      /** Byline. Defaults to the company. */
      author: z.string().default("Comet National"),
      /** Optional topical tags for grouping / future filtering. */
      tags: z.array(z.string()).default([]),
      /** Optional editorial category shown as the eyebrow / OG kicker. */
      category: z.string().optional(),
      /** Optional co-located hero image; also used as the social image. */
      heroImage: image().optional(),
      /** Optional alt text for the hero image. */
      heroAlt: z.string().optional(),
      /** Optional explicit OG image (absolute URL or site-relative path). */
      ogImage: z.string().optional(),
    }),
});

export const collections = { posts };
